# Generated by Django 4.0.5 on 2022-12-21 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_quotes_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotes',
            name='name',
        ),
    ]
