# Generated by Django 4.0.5 on 2023-01-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_quotes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
